version: '3'

services:
  django:
    build: .
    command: bash -c "python src/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
