# Generated by Django 2.1 on 2018-08-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='mysite/shop/static/shop/image/goods/')),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='mysite/shop/static/shop/image/cat/'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
    ]
