# Generated by Django 2.1 on 2018-09-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_goods_is_recommend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'slide', 'verbose_name_plural': 'slides'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('category', 'title'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='goods',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='is_top'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.FileField(upload_to='image/carousel/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.CharField(max_length=200, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='image/cat/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is_published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(upload_to='image/goods/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is_published'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='is_recommend'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.TextField(verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='tel',
            field=models.CharField(max_length=100, verbose_name='tel'),
        ),
    ]
