# Generated by Django 2.1 on 2018-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180825_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(),
        ),
    ]
