# Generated by Django 2.1 on 2018-08-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180825_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='image/carousel/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='image/cat/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(upload_to='image/goods/'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
